name: Deploy Portfolio to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # O passo de criar o config está correto e fica
      - name: Criar next.config.js para Produção
        run: |
          cat << EOT > next.config.js
          /** @type {import('next').NextConfig} */
          const nextConfig = {
            output: 'export',
            images: {
              unoptimized: true,
            },
          };

          module.exports = nextConfig;
          EOT

      - name: Build project
        run: npm run build

      # O passo de listar os arquivos está correto e fica
      - name: Listar conteúdo da pasta 'out'
        run: ls -R out

      # --- MUDANÇA TOTAL DO DEPLOY ---
      # Trocamos a action 'SamKirkland' pela 'lftp-action'
      - name: Deploy to FTP via LFTP
        uses: wearerequired/lftp-action@v2
        with:
          # Define as variáveis de ambiente com seus secrets
          env:
            FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
            FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
            FTP_SERVER: ${{ secrets.FTP_SERVER }}
          
          # O comando 'lftp' que vamos rodar
          run: |
            # Conecta ao servidor (sem SSL, que pode ser um problema)
            lftp -c "set ftp:ssl-allow no; 
            open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER;
            
            # Sincroniza a pasta 'out' com a raiz do servidor '.'
            # -R (upload), -n (só novos), -e (deleta antigos), -v (verboso)
            mirror -Rnev ./out ./
            "
