name: Deploy Portfolio to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # --- A CORREÇÃO ESTÁ AQUI ---
      # Forçamos o NODE_ENV=production para que o
      # next.config.js ative o 'output: "export"'
      - name: Build project
        run: NODE_ENV=production npm run build

      - name: Listar arquivos após o build (para diagnóstico)
        run: ls -R

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: ./public_html/
          dangerous-clean-slate: true
