name: Deploy Portfolio to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # --- A SOLUÇÃO DEFINITIVA ESTÁ AQUI ---
      # Modifica o next.config.js SÓ NO SERVIDOR DE BUILD
      # Adiciona a linha "  output: 'export'," logo após "const nextConfig = {"
      # Isso não afeta seu arquivo local.
      - name: Adicionar 'output: export' ao next.config.js
        run: |
          sed -i "/const nextConfig = {/a \ \ output: 'export'," next.config.js

      - name: Build project
        run: npm run build

      - name: Listar arquivos (para ver se 'out' está cheio)
        run: ls -R

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: ./public_html/
          dangerous-clean-slate: true
